import h5py
import numpy as np
import json
import sys
from pathlib import Path

def compute_session_stats(h5_files):
    stats = {}
    for file_path in h5_files:
        try:
            with h5py.File(file_path, 'r') as f:
                all_trials = []
                for trial_name in f.keys():
                    trial_group = f[trial_name]
                    
                    # Try different possible neural data keys
                    neural_data = None
                    if 'input_features' in trial_group:
                        neural_data = trial_group['input_features'][:]
                    elif 'tx1' in trial_group:
                        neural_data = trial_group['tx1'][:]
                    elif 'neural_features' in trial_group:
                        neural_data = trial_group['neural_features'][:]
                    else:
                        # Print available keys for debugging
                        print(f"Warning: Trial {trial_name} in {file_path} has no recognized neural data key")
                        print(f"  Available keys: {list(trial_group.keys())}")
                        continue
                    
                    all_trials.append(neural_data)
                
                if not all_trials:
                    print(f"Skipping {file_path} - no valid neural data found")
                    continue
                
                # Combine all trials in this session to get 'Global' stats
                session_data = np.concatenate(all_trials, axis=0)
                
                stats[file_path] = {
                    "mean": session_data.mean(axis=0).tolist(),
                    "std": session_data.std(axis=0).tolist()
                }
                print(f"✓ Stats computed for {file_path}")
                
        except Exception as e:
            print(f"✗ Error processing {file_path}: {str(e)}")
            continue
    
    if stats:
        # Save to JSON so you don't have to re-run this
        with open('session_stats.json', 'w') as j:
            json.dump(stats, j)
        print(f"\n✓ Saved statistics for {len(stats)} sessions to session_stats.json")
    else:
        print("No statistics computed")

if __name__ == "__main__":
    # Load h5_list from the JSON file generated by trainingdata_list.py
    
    filepath = r"C:\Projects\Brain2Text2025\brain2text2025\src\utils\h5_list_data.json"
    with open(filepath, "r") as file:
        h5_list = json.load(file)        
    
    print(f"Found {len(h5_list)} HDF5 files to process")
    print("Computing session statistics...\n")
    
    # Run the function
    compute_session_stats(h5_list)